"""removed depth

Revision ID: c0bfe0f9c666
Revises: 52cacc2ab734
Create Date: 2025-09-11 11:42:03.857770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bfe0f9c666'
down_revision = '52cacc2ab734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('earthquakes', 'depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('depth', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
